services:
  server:
    build: server
    env_file:
      - .env
    ports:
      - ${FORTUNE_SERVER_PORT}:8080
    secrets:
      - db-password.txt
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    build: db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${FORTUNE_DB_USER}
      POSTGRES_PASSWORD_FILE: ${FORTUNE_DB_PASSWORD_FILE}
      POSTGRES_DB: ${FORTUNE_DB_NAME}
    ports:
      - ${FORTUNE_DB_PORT}:5432
    secrets:
      - db-password.txt
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${FORTUNE_DB_USER} -d ${FORTUNE_DB_NAME}"]

volumes:
  db-data:

secrets:
  db-password.txt:
    file: secrets/db-password.txt
